defaults: &defaults
  fedex:
    account: <%= ENV['FEDEX_ACCOUNT'] %>
    meter: <%= ENV['FEDEX_METER'] %>
  ups:
    key: <%= ENV['UPS_KEY'] %>
    login: <%= ENV['UPS_LOGIN'] %>
    pass: <%= ENV['UPS_PASSWORD'] %>
  usps:
    user: <%= ENV['USPS_USER'] %>

development:
  <<: *defaults
    
test:
  <<: *defaults
